package application;
import java.util.LinkedList;
import javax.swing.JFileChooser;
/**
*
* @author Anjola Olarinde
*/
/**
 * This class gives the user an interface to work with the Listserv classes.
 * 
 * @author <pre>Anjola Olarinde, C/4C, AFROTC</pre>
 * <pre>Deputy Technology Officer, Detachment 330</pre>
 * <pre>April 2017</pre>
 * 
 */
public class ListservGUI extends javax.swing.JFrame {

   /**
    * Creates new form ListservGUI
    */
   final String DEFAULTEMAIL = "email@site.com email2@site2.com";
   ListservFill fill;
   Instruction ints;
   
   public ListservGUI() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

       addOrDeleteGroup = new javax.swing.ButtonGroup();
       jFrame1 = new javax.swing.JFrame();
       jFileChooser1 = new javax.swing.JFileChooser();
       jPanel1 = new javax.swing.JPanel();
       titleLabel = new javax.swing.JLabel();
       sendButton = new javax.swing.JButton();
       textScrollPanel = new javax.swing.JScrollPane();
       emailText = new javax.swing.JTextArea();
       emailLabel = new javax.swing.JLabel();
       addRadio = new javax.swing.JRadioButton();
       removeRadio = new javax.swing.JRadioButton();
       chooser = new javax.swing.JButton();
       instructionButton = new javax.swing.JButton();

       javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
       jFrame1.getContentPane().setLayout(jFrame1Layout);
       jFrame1Layout.setHorizontalGroup(
           jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 400, Short.MAX_VALUE)
           .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jFrame1Layout.createSequentialGroup()
                   .addGap(0, 0, Short.MAX_VALUE)
                   .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGap(0, 0, Short.MAX_VALUE)))
       );
       jFrame1Layout.setVerticalGroup(
           jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGap(0, 300, Short.MAX_VALUE)
           .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jFrame1Layout.createSequentialGroup()
                   .addGap(0, 0, Short.MAX_VALUE)
                   .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addGap(0, 0, Short.MAX_VALUE)))
       );

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       titleLabel.setText("AFROTC DET330 LISTSERV ADD/DELETE");

       sendButton.setText("SEND");
       sendButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               sendButtonActionPerformed(evt);
           }
       });

       emailText.setColumns(20);
       emailText.setRows(5);
       emailText.setText("email@site.com\nemail2@site2.com");
       textScrollPanel.setViewportView(emailText);

       emailLabel.setText("Emails:");

       addOrDeleteGroup.add(addRadio);
       addRadio.setText("Add");
       addRadio.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               addRadioActionPerformed(evt);
           }
       });

       addOrDeleteGroup.add(removeRadio);
       removeRadio.setText("Remove");
       removeRadio.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               removeRadioActionPerformed(evt);
           }
       });

       chooser.setText("Open File");
       chooser.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               chooserActionPerformed(evt);
           }
       });

       instructionButton.setText("View Intructions");
       instructionButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               instructionButtonActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(76, 76, 76)
                       .addComponent(titleLabel))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(emailLabel)
                       .addGap(78, 78, 78)
                       .addComponent(instructionButton))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(161, 161, 161)
                       .addComponent(sendButton))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(113, 113, 113)
                       .addComponent(addRadio)
                       .addGap(51, 51, 51)
                       .addComponent(removeRadio)))
               .addContainerGap(74, Short.MAX_VALUE))
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(textScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(chooser)
               .addGap(40, 40, 40))
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(titleLabel)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(0, 28, Short.MAX_VALUE)
                       .addComponent(emailLabel))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(instructionButton)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(textScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(addRadio)
                           .addComponent(removeRadio))
                       .addGap(1, 1, 1)
                       .addComponent(sendButton))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(53, 53, 53)
                       .addComponent(chooser)))
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );

       pack();
   }// </editor-fold>//GEN-END:initComponents

   private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
      
       //If you have not changed the string, then remove the beginning
       if(emailText.getText().contains(DEFAULTEMAIL))
           emailText.setText(emailText.getText().substring(DEFAULTEMAIL.length()-1));
       if(emailText.getText().equals(""))
       {  //do nothing  
           return;
       } 
       LinkedList<String> list = new LinkedList<String>();
       String[] email = emailText.getText().split("[^A-Za-z0-9@.]");
       if(removeRadio.isSelected())
           for(String s: email)
               ListservFill.leave(s);
       else if(addRadio.isSelected())
           for(String s: email)
               ListservFill.join(s);
   }//GEN-LAST:event_sendButtonActionPerformed

   private void addRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRadioActionPerformed
       // TODO add your handling code here:
   }//GEN-LAST:event_addRadioActionPerformed

   private void removeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRadioActionPerformed
       // TODO add your handling code here:
   }//GEN-LAST:event_removeRadioActionPerformed

   private void chooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooserActionPerformed
//          // TODO add your handling code here: 
//       chooser.setFileSelectionMode(JFileChooser.FILES_ONLY); 
//       int returnVal = chooser.showOpenDialog((java.awt.Component) null); 
//       
//       if ( returnVal == chooser.APPROVE_OPTION ) { 
//           
//           java.io.File inFile = chooser.getSelectedFile(); 
//           
//           processFile(inFile); 
//       } 
   }//GEN-LAST:event_chooserActionPerformed

   private void instructionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionButtonActionPerformed
       // TODO add your handling code here:
       if(ints == null)
       {
           ints = new Instruction();
       }
       ints.setVisible(true);        
   }//GEN-LAST:event_instructionButtonActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(ListservGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(ListservGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(ListservGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(ListservGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new ListservGUI().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.ButtonGroup addOrDeleteGroup;
   private javax.swing.JRadioButton addRadio;
   private javax.swing.JButton chooser;
   private javax.swing.JLabel emailLabel;
   private javax.swing.JTextArea emailText;
   private javax.swing.JButton instructionButton;
   private javax.swing.JFileChooser jFileChooser1;
   private javax.swing.JFrame jFrame1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JRadioButton removeRadio;
   private javax.swing.JButton sendButton;
   private javax.swing.JScrollPane textScrollPanel;
   private javax.swing.JLabel titleLabel;
   // End of variables declaration//GEN-END:variables
}